//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountCode { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Avatar { get; set; }
        public string RequestCode { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_At { get; set; }
    }
}
