//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int AccountCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> BrandCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public string ImageProduct { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<double> Rate { get; set; }
    }
}
