//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactCode { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> AccountCode { get; set; }
    }
}
