//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderCode { get; set; }
        public Nullable<int> PaymentCode { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string OrderNote { get; set; }
        public Nullable<int> AccountAddressCode { get; set; }
    }
}
