//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentCode { get; set; }
        public string PaymentType { get; set; }
        public string AccountNumer { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
